article/urls.py
from django.urls import path,include
from article import views
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    # path('article-delete/<int:id>', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),

]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
# 新引入的模块
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 文章模块
    path('article/', include('article.urls', namespace='article')),
    # 用户模块
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # 评论模块
    path('comment/', include('comment.urls', namespace='comment')),

]

#添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path, re_path, include
from userprofile import views
app_name = 'userprofile'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>', views.user_delete, name='delete'),
    path('reset/', views.user_reset, name='reset'),
    path('forget/<str:token>', views.user_forget, name='forget'),
    path('forget1/', views.user_forget1, name='forget1'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),

]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# 引入内置信号
from django.db.models.signals import post_save
# 引入信号接收器的装饰器
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20, blank=True)
    # 头像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    # 个人简介
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

userprofile/forms.py
# --*-- coding: utf-8 --*--
# @Time     : 2020/9/19 15:40
# @Author   : mrqinglang
# @software : PyCharm
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')
    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError('密码输入不一致,请重试。')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

userprofile/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from userprofile.forms import UserLoginForm, UserRegisterForm
from django.contrib.auth.models import User
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required
# 加密
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from my_blog import settings
import random
import re
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password, check_password
from userprofile.forms import ProfileForm
from userprofile.models import Profile


# Create your views here.

def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # cleaned_data 就是读取表单返回的值，返回类型为字典dict型
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                login(request, user)
                return redirect('article:article_list')
            else:
                return render(request, 'userprofile/login.html', {'errmsg': '账号密码不合法'})
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse('请使用GET或POST')

def user_logout(request):
    logout(request)
    return redirect('userprofile:login')

def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        username = request.POST.get('username')
        pwd = request.POST.get('password')
        pwd2 = request.POST.get('password2')
        email = request.POST.get('email')

        try:
             user = User.objects.get(username=username)
        except User.DoesNotExist:
            # 用户名不存在
               user = None
        if user:
            # 用户名已存在
            return render(request, 'userprofile/register.html', {'errmsg': '用户名已存在'})
        if email:
            if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
                return render(request, 'userprofile/register.html', {'errmsg': '请检查邮箱是否正确'})
        if pwd != pwd2:
            return render(request, 'userprofile/register.html', {'errmsg': '两次密码不一致'})
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            login(request, new_user)
            return redirect('article:article_list')


    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse('请提交get或post请求')

#@login_required是一个Python装饰器。装饰器可以在不改变某个函数内容的前提下，
# 给这个函数添加一些功能。具体来说就是@login_required要求调用user_delete()函数时，
# 用户必须登录；如果未登录则不执行函数，将页面重定向到/userprofile/login/地址去。
@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        if request.user == user:
            logout(request)
            user.delete()
            return redirect('userprofile:login')
        else:
            return HttpResponse('你没有删除操作的权限。')
    else:
        return HttpResponse('仅接受post请求。')


def user_reset(request):
    if request.method == 'GET':

        return render(request, 'userprofile/reset.html')
    elif request.method == 'POST':
        email = request.POST.get('email')
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            return HttpResponse('邮箱错误')
        num = random.randint(1000, 9999)
        serializer = Serializer(settings.SECRET_KEY, 3600)
        info = {'num': num}
        token = serializer.dumps(info)
        token = token.decode('utf8')  # 编码里面不写默认为utf8
        # 发邮件
        subject = '密码重置'  # 标题
        message = '<h1> 您的验证码为%s<h1 />' \
                  '<a href="http://127.0.0.1:8000/userprofile/forget/%s">修改密码</a>' % (
                  num, token)
        #           'http://127.0.0.1:8000/user/registe/'  # 内容
        # sender = settings.EMAIL_BACKEND
        sender = settings.EMAIL_HOST_USER
        receiver = [email]
        send_mail(
            subject,
            '',
            sender,
            receiver,
            html_message=message)
        return redirect('userprofile:login')

    else:
        return HttpResponse('请返回get和post请求')

def user_forget(request,token):
    if request.method == 'GET':
        res = render(request, 'userprofile/forget.html')
        res.set_cookie('info', token)
        return res

def user_forget1(request):
    if request.method == 'POST':
        token = request.COOKIES.get('info')
        serializer = Serializer(settings.SECRET_KEY, 3600)
        # print(token)
        info = serializer.loads(token)
        try:
            username = request.POST.get('username')
            pwd = request.POST.get('pwd')
            pwd1 = request.POST.get('pwd1')
            num = request.POST.get('num')
            if not all([username, pwd, pwd1, num]):
                # 数据不完整
                return render(request, 'userprofile/forget.html', {'errmsg': '数据不完整，请重新填写'})
            if num != str(info['num']):
                return render(request, 'userprofile/forget.html', {'errmsg': '验证码错误'})
            Use = User.objects.get(username=username)
            try:
                Use = User.objects.get(username=username)
            except Use.DoesNotExist:
                # 用户名不存在
                Use = None
            if  Use == None:
                # 用户名已存在
                return render(request, 'userprofile/forget.html', {'errmsg': '用户名不存在'})
            if pwd != pwd1:
                return render(request, 'userprofile/forget.html', {'errmsg': '两次密码输入不一致'})
            password = make_password(pwd)
            Use.password = password
            Use.save()
            return redirect('userprofile:login')
        except SignatureExpired as e:
            # 激活时间过期
            return render(request, 'userprofile/forget.html', {'errmsg': '激活时间已过期'})

@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    # user_id 是 OneToOneField 自动生成的字段
    # profile = Profile.objects.get(user_id=id)
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)

    if request.method == 'POST':
        # 验证修改数据者，是否为用户本人
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息。")
        # 修改本行
        # 上传的文件保存在 request.FILES 中，通过参数传递给表单类
        profile_form = ProfileForm(request.POST, request.FILES)
        # profile_form = ProfileForm(data=request.POST)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']
            # 如果 request.FILES 存在文件，则保存
            if 'avatar' in request.FILES:
                profile.avatar = profile_cd["avatar"]
            profile.save()
            # 带参数的 redirect()
            return redirect("userprofile:edit", id=id)
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = {'profile_form': profile_form, 'profile': profile, 'user': user }
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

templates/userprofile/edit.html
{% extends "base.html" %} {% load static %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <br>
            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">暂无头像</h5>
            {% endif %}
            <br>
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                    <!-- avatar -->
                <div class="form-group">
                    <label for="avatar">
                        {% if profile.avatar %}
                            重置头像
                        {% else %}
                            上传头像
                        {% endif %}
                    </label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/forget.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" action="{% url 'userprofile:forget1' %}">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <div class="form-group">
                    <label for="pwd">密码</label>
                    <input type="password" class="form-control" id="pwd" name="pwd">
                </div>
                <div class="form-group">
                    <label for="pwd1">确认密码</label>
                    <input type="password" class="form-control" id="pwd1" name="pwd1">
                </div>
                <div class="form-group">
                    <label for="num">验证码</label>
                    <input type="text" class="form-control" id="num" name="num">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
                {% if errmsg %}
                    <br />
                    <div style="color: red">{{ errmsg }}</div>
                {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <h5>还没有账号？</h5>
            <h5>点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！</h5>
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
            {% if errmsg %}
                <br>
                <div style="color: red">{{ errmsg }}</div>
                <br>
                <h5>忘记密码了？</h5>
                <h5>点击<a href='{% url "userprofile:reset" %}'>这里</a>重置密码</h5>
                {% endif %}

        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/register.html
{% extends 'base.html' %}{% load static %}
{% block title %}{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group col-md-4">
                        <label for="username">昵称</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <!-- 邮箱 -->
                    <div class="form-group col-md-4">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group col-md-4">
                        <label for="password">设置密码</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <!-- 确认密码 -->
                    <div class="form-group col-md-4">
                        <label for="password2">确认密码</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
                {% if errmsg %}
                    <br />
                    <div style="color: red">{{ errmsg }}</div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/userprofile/reset.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="email">邮箱</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}